// This file is generated by Slice Machine. Update with care!

import ButtonRow from './ButtonRow'
import Hero from './Hero'
import Image from './Image'
import TextBlock from './TextBlock'

export { ButtonRow, Hero, Image, TextBlock }

export const components = {
  button_row: ButtonRow,
  hero: Hero,
  image: Image,
  text_block: TextBlock,
}
